---
  -hosts: all
   sudo: yes
   tasks:
   - name: Ensure NTP is installed and synched
     yum: name=ntp state=present
   - name: Ensure NTP is running
     service: name=ntpd state=started enabled=yes 
